notification_feed_test.go, options.go
Be sure to urlencode query params when passing request options.
=> urlencode query params

client.go, client_test.go, types.go
Add support for batch unfollow endpoint for enabled apps.
=> Batch unfollow endpoint

collections.go, collections_test.go, types.go
=> Remove Name from CollectionObject

.vscode/settings.json, README.md, activity.go, aggregated_feed.go, aggregated_feed_test.go, authenticator.go, client.go, collections.go, collections_test.go, enriched_activities.go, flat_feed.go, flat_feed_test.go, notification_feed.go, notification_feed_test.go, options.go, reactions.go, reactions_test.go, types.go, users.go, users_test.go
Add Collections, Users, Reactions, Enrichment.
This will require a major version release because it breaks backwards compatibility with the batch collections endpoints
=> [AC-99] Collections, Users, Reactions, Enrichment

options.go, types.go, types_internal_test.go, utils.go
Add missing enrichment params to GetActivtiesOptions
=> add enrichment options to fetch activities

client.go, iface.go
=> add client interface

.github/workflows/go.yml, .golangci.yml, activity.go, activity_test.go, aggregated_feed_test.go, analytics.go, analytics_test.go, authenticator.go, client_test.go, collections.go, collections_test.go, enriched_activities.go, enriched_activities_test.go, errors_test.go, feed_test.go, flat_feed_test.go, go.sum, notification_feed_test.go, options.go, personalization.go, reactions.go, reactions_test.go, run-lint.sh, types.go, types_test.go, users.go, users_test.go, utils.go, utils_test.go
add golangci and impi, and fix their issues.
=> Add lint before v4 tag

client.go, client_test.go, types.go
=> Add enrich activity getters

collections.go, users.go
that doesn't require a client.
Fixes #32
=> Add convenience helpers for refs

.golangci.yml
* Add bodyclose to lint
* Enable all rules from vet
=> Improve lint config

iface.go
=> Extend client interface for enrich

authenticator.go, client.go, client_test.go, go.mod, go.sum
Same package was imported in two ways, ensure it's imported consistently.
=> Drop gopkg.in in favor of direct

.github/workflows/go.yml, README.md
- run push on master
- run only pull request for pull request
=> Do not run push and pull request at the same time

client.go
Also add clone with new timeout to update.
=> Support client timeouts

README.md, activity_test.go, aggregated_feed_test.go, analytics_test.go, client.go, client_test.go, collections_test.go, enriched_activities_test.go, errors_test.go, feed.go, feed_test.go, flat_feed_test.go, go.mod, go.sum, notification_feed_test.go, reactions_test.go, types.go, types_test.go, users_test.go, utils_test.go
* update readme for examples and install
* fix couple existing issues in readme
* add interface satisfaction
* provide richer response for a few endpoints (remove, to targets, etc.)
=> Update readme and satisfy interfaces

client.go, feed_test.go, types.go
* fixed a typo in json key
* add base response to one forgotten endpoint
=> Overload unmarshal to fix inlined struct

client_test.go, run-lint.sh, types.go
=> Add NewUnfollowRelationship helper

.github/workflows/go.yml, .gitignore, .golangci.yml, feed.go, go.sum, run-lint.sh, types.go
for memory alignment but disabled in general since requires not intuitive field ordering
=> Bump go versions and small improvements

client.go, flat_feed.go, flat_feed_test.go, options.go, types.go
=> Add follow stats support

.gitignore, client.go, feed.go, flat_feed.go
**What does this PR do?**
- fixes minor typos in docs
@ferhatelmas found some minor typos so raised a PR, hope this is fine 😃
=> Fix minor typos

.github/workflows/reviewdog.yml, .golangci.yml
=> embed aggregated feed

options.go, types.go
Added option `WithEnrichUserReactions` to filter reactions by user id:
```
opts := []stream.GetActivitiesOption{
stream.WithEnrichOwnReactions(),
stream.WithEnrichUserReactions("user123"),
}
```
=> [PBE-787] filter reactions by user id
