GetStream/stream-go2

aggregated_feed_test.go, client.go, client_internal_test.go, flat_feed_test.go, notification_feed_test.go, options.go
Instead of using strings and concatenation/manipulation for URLs, queries, etc., just rely on the `net/url` package and its types.
=> Use url.URL and related instead of strings

aggregated_feed.go, aggregated_feed_test.go, flat_feed.go, flat_feed_test.go, notification_feed.go, notification_feed_test.go, options.go, types.go, utils.go
This PR adds a `GetNextPageActivities` to Flat, Aggregated, and Notification feeds types that allows to easily retrieve the next page in a paginated result directly from a `GetActivities` response.
Example:
```go
feed, err := client.FlatFeed("user", "123")
if err != nil { /* ... */ }
resp, err := feed.GetActivities()
if err != nil { /* ... */ }
nextResp, err := feed.GetNextPageActivities(resp)
if err != nil { /* ... */ }
```
=> Add GetNextPageActivities to Feed implementations

client_test.go, types.go
This adds the possibility to add an activity copy limit to a batch follow single request.
=> add activity copy limit support in body for batch follow

url.go, url_internal_test.go
Override regions with defaults for easier client initialization when using `WithAPIRegion`.
=> Regions overrides

options.go
When following feeds w/ zero activity copy limit client sends request to Stream servers w/ default activity copy limit of 100
This is due to `omitempty` json annotation.
I propose removal of this annotation as `ActivityCopyLimit` is always initialised to default value in the code before applying any user provided options.
=> Allow following w/ zero activity copy limit

authenticator.go, client.go, client_test.go, types.go
Add support for the new `GET /activities/` endpoint which allows to retrieve an app's activities by ID or foreign ID and timestamp.
=> Support activities GET endpoint

client.go, feed.go, feed_test.go
The `UpdateActivities` in unrelated to a specific field, hence should be moved from the `Feed` interface to the `Client` type.
=> Move UpdateActivities to Client level

enriched_activities.go, enriched_activities_test.go, stream.go, types.go, utils.go, utils_internal_test.go
This adds a struct for the enriched activity, similar to the `Activity` struct.
The fields were taken from https://github.com/GetStream/stream-java/blob/47add14b35951b17ce5aa45716f1e66eba69788e/src/main/java/io/getstream/core/models/EnrichedActivity.java and based on my own testing.
I also added an `EnrichedReaction` struct since it includes more fields than the `Reaction`. I tested on my own app and it seems that `created_at` and `updated_at` use a different time format than the other fields in the API; they also seem to include the timezone (only `Z` though).
I'm not sure if `MarshalJSON` is required for `EnrichedActivity` since it will never be serialized, but this is simply a copy from `Activity`.
=> Add struct for enriched activity

feed.go
Was reading through source code and noticed each call to `newFeed` would compile regex, it also wouldn't catch an invalid regex unless `newFeed` was called.
This change makes it so that the regex is compiled once globally, and will panic if the regex is invalid on import, rather than when `newFeed` is called.
=> Compile user id regex once instead of per request

.github/workflows/go.yml, .gitignore, .golangci.yml, authenticator.go, go.mod, run-lint.sh
* Drop go1.12 and support go1.14
* Bump golangci-lint to the latest and add unused linter
* Drop unused / unexported code
* Add vscode to gitignore
=> Bump go and lint

activity.go, authenticator.go, client.go, collections.go, enriched_activities.go, errors.go, personalization.go, types.go, utils.go
This change updates how errors are created. When looking through source code I noticed a few things:
* `fmt.Errorf` was used in situations where the error strings had no formatting directives
* When `fmt.Errorf` was used to wrap an error, the `%s` directive was being used
This modifies the source to use `errors.New` when not explicitly formatting an error, I didn't change usage in tests, just in client code. 
It also modifies calls for `fmt.Errorf` to use the `%w` directive to wrap errors instead of `%s`, this way clients can take advantage of [go 1.13 error wrapping](https://blog.golang.org/go1.13-errors)
=> Use errors.New when not formatting and use %w directive when wrapping errors

client.go
Otherwise, >299 status code, body isn't closed.
=> Close response body correctly

analytics.go, analytics_test.go, client.go, client_internal_test.go, collections.go, collections_test.go, errors.go, personalization.go, personalization_test.go, reactions.go, reactions_test.go, types.go, users.go, users_test.go, utils.go
Or on error unless status code is success.
Rate limit is added to personalization but
actually server doesn't serve it so it will be empty.
Missing read support will be addressed in #71 and 
then it will be used.
Fixes #59
=> Expose rate limit headers in responses

collections.go, types.go
Due to server response structure, there is nesting in the type but it makes common sense longer so hide it.
=> Reduce nesting for user convenience

utils_test.go
Using byte compare for json in tests is error prone for 
* field order change
* whitespace
etc.
instead use json equal to make it more robust to changes.
Side benefit, it can generate better diffs unless equal.
=> Use json compare to handle syntactic differences in tests

reactions_test.go, types.go
While a reaction is being added, it can generate activities on `target_feeds`.
Normally, client can pass extra data to be put into these activities. This support is added.
=> Add extra data for target feeds

client.go
Adding this method would simplify being able to instantiate a feed where I don't care about the particular type, as raised in #82
=> Allow creating generic feed using target id

client.go, feed.go, run-lint.sh
Make feed slug-id separator a constant.
Use match string for regex while checking feed id,
instead of copying.
Bump lint tool.
=> Small general improvements

enriched_activities.go, types.go, types_test.go
https://github.com/fatih/structs doesn't handle nested structs properly so handle the case for enriched activities custom.
Moreover, above package is archived and no support anymore, it seems better to drop it.
fixes #85
=> Fix marshal of enriched activity

enriched_activities.go, types_test.go
=> Improve the test of marshal for structs bug

authenticator.go, client.go, client_test.go, go.mod, go.sum
- [dgrijalva/jwt-go](https://github.com/dgrijalva/jwt-go) is not maintained anymore
- patch version bump for mitchellh/mapstructure
=> Switch to golang-jwt/jwt/v4

enriched_activities.go, enriched_activities_test.go
Referenced activity in `foreign_id` if enriched would be an object. 
Enriched object is unmarshaled to `foreign_id_ref` in `Extra` and id is extracted to `ForeignID` in activity.
Data can't break SDK.
=> Handle activity references in enrichment
